# Generated by Django 5.2.17 on 2026-08-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "issuer",
                    models.CharField(
                        blank=True,
                        help_text="Say who actually issued it.",
                        max_length=140,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Optional qualifier, e.g. 'self-study course, not an exam certification'.",
                        max_length=140,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification", models.CharField(max_length=180)),
                ("institution", models.CharField(max_length=180)),
                ("date_range", models.CharField(max_length=80)),
                (
                    "grade",
                    models.CharField(
                        blank=True, help_text="e.g. 'Distinction'", max_length=60
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=140)),
                ("organisation", models.CharField(max_length=180)),
                (
                    "date_range",
                    models.CharField(
                        help_text="e.g. 'Aug 2026 – Present'", max_length=80
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, help_text="e.g. 'UK'", max_length=80),
                ),
                (
                    "is_technical",
                    models.BooleanField(
                        default=False,
                        help_text="Tick for software roles — these are highlighted in the timeline.",
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = top of the timeline."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Experience",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExploringArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "grounding",
                    models.TextField(
                        help_text="The line explaining what real work this builds on."
                    ),
                ),
                (
                    "status_label",
                    models.CharField(default="CURRENTLY LEARNING", max_length=60),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(default="Suraj Pandey", max_length=120)),
                (
                    "initials",
                    models.CharField(
                        default="SP",
                        help_text="Shown in the nav logo badge.",
                        max_length=4,
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="suraj.dev",
                        help_text="Wordmark next to the badge.",
                        max_length=60,
                    ),
                ),
                (
                    "role_title",
                    models.CharField(
                        default="Software Engineer — Python · Django · React · TypeScript",
                        max_length=200,
                    ),
                ),
                (
                    "availability_note",
                    models.CharField(
                        blank=True,
                        default="Open to UK roles · Graduate visa",
                        help_text="Small pill above your name. Leave blank to hide it.",
                        max_length=140,
                    ),
                ),
                (
                    "hero_intro",
                    models.TextField(
                        default="", help_text="One or two sentences under your name."
                    ),
                ),
                (
                    "about_heading",
                    models.CharField(
                        default="A developer who ships, end to end", max_length=140
                    ),
                ),
                (
                    "about_body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Separate paragraphs with a blank line.",
                    ),
                ),
                (
                    "exploring_tags",
                    models.CharField(
                        blank=True,
                        default="AI/ML · Cybersecurity · DevOps",
                        help_text="Small text under the 'Exploring' link in the hero.",
                        max_length=200,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="surajpande20554@gmail.com", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="+44 7587 546294", max_length=40
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, default="London, UK", max_length=120),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, default="https://github.com/surazzpande"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, default="https://linkedin.com/in/surajpande-dev"
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Upload your CV as a PDF — the 'Download Resume' button links to it.",
                        null=True,
                        upload_to="resume/",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
            ],
            options={
                "verbose_name": "Profile & contact details",
                "verbose_name_plural": "Profile & contact details",
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="e.g. 'Backend'", max_length=80)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Skill categories",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="e.g. '3+' or 'Distinction'", max_length=30
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. 'YEARS EXPERIENCE'", max_length=60
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EducationBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="portfolio.education",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="portfolio.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExploringTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="portfolio.exploringarea",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="The line under the title.",
                        max_length=300,
                    ),
                ),
                (
                    "problem",
                    models.TextField(
                        blank=True, help_text="Shown after the PROBLEM label."
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True, help_text="Shown after the SOLUTION label."
                    ),
                ),
                (
                    "code_url",
                    models.URLField(blank=True, help_text="Link to the repository."),
                ),
                (
                    "live_url",
                    models.URLField(
                        blank=True, help_text="Optional link to a live demo."
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured projects show a highlight border.",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide without deleting."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="portfolio.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="experiences", to="portfolio.tag"
            ),
        ),
    ]
