# Generated by Django 5.2.17 on 2026-08-22 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gh_forks",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="GitHub forks"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gh_language",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Main language"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gh_pushed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last commit"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gh_stars",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="GitHub stars"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gh_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Stats last refreshed"
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Leave blank and it is generated from the title.",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="One or two sentences shown on the blog listing and in search results.",
                        max_length=400,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Separate paragraphs with a blank line. Start a line with '## ' for a subheading, '- ' for a bullet, and wrap code in a line of ``` above and below."
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Drafts are only visible to you while logged into the admin.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Used for ordering and shown on the post.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="portfolio.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
