# Generated by Django 5.2.17 on 2026-08-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_gh_forks_project_gh_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="completed_on",
            field=models.DateField(
                blank=True,
                help_text="When you finished it. Leave blank if still in progress.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="credential_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="certification",
            name="credential_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the certificate or credential page, so it can be verified.",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="expires_on",
            field=models.DateField(
                blank=True, help_text="Only if the certification expires.", null=True
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("certification", "Certification (passed an exam)"),
                    ("course", "Course / training"),
                    ("degree", "Degree or diploma"),
                    ("other", "Other"),
                ],
                default="course",
                help_text="Be accurate: only pick 'Certification' if you sat and passed the exam.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0–100. Only shown while the status is 'In progress'.",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="published",
            field=models.BooleanField(
                default=True, help_text="Untick to hide without deleting."
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In progress"),
                    ("planned", "Planned"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="issuer",
            field=models.CharField(
                blank=True, help_text="Who actually issued it.", max_length=140
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Optional qualifier, e.g. 'self-study course, not an exam certification'.",
                max_length=160,
            ),
        ),
    ]
